apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync-serverfiles
  namespace: udl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync-serverfiles
  template:
    metadata:
      labels:
        app: git-sync-serverfiles
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.5.1
          args:
            - --repo=https://github.com/UDL-TF/ServerFiles
            - --username=x-access-token
            - --password-file=/etc/github-token/password
            - --root=/mnt
            - --dest=serverfiles
            - --period=60s
            - --sync-timeout=5m
            - --max-failures=0
          volumeMounts:
            - name: serverfiles
              mountPath: /mnt
            - name: github-token
              mountPath: /etc/github-token
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: serverfiles
          hostPath:
            path: /mnt/serverfiles
            type: DirectoryOrCreate
        - name: github-token
          secret:
            secretName: github-token