apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        forwardedHeaders:
          trustedIPs:
            - 10.42.0.0/16   # Pods CIDR
            - 10.43.0.0/16   # Services CIDR
        proxyProtocol:
          trustedIPs:
            - 10.42.0.0/16
            - 10.43.0.0/16
      websecure:
        forwardedHeaders:
          trustedIPs:
            - 10.42.0.0/16
            - 10.43.0.0/16
        proxyProtocol:
          trustedIPs:
            - 10.42.0.0/16
            - 10.43.0.0/16
    service:
      spec:
        externalTrafficPolicy: Local